"""
report_writer.py — Formats the full weekly Markdown report.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

import config

_RAG_EMOJI = {"Green": "🟢", "Amber": "🟡", "Red": "🔴"}


def _rag_badge(rag: str) -> str:
    return f"{_RAG_EMOJI.get(rag, '⚪')} **{rag}**"


def _mc_section(mc: dict) -> str:
    if mc.get("p_on_time") is None:
        return f"> ⚠️ {mc.get('caveat', 'Monte Carlo unavailable.')}\n"
    return (
        f"| Metric | Value |\n|--------|-------|\n"
        f"| Deadline | {mc['deadline']} |\n"
        f"| **P(on time)** | **{mc['p_on_time']*100:.0f}%** |\n"
        f"| P(slip 1 week) | {mc.get('p_slip_1w', 0)*100:.0f}% |\n"
        f"| P(slip 2+ weeks) | {mc.get('p_slip_2w_plus', 0)*100:.0f}% |\n"
        f"| Median finish | {mc.get('median_finish_date', 'N/A')} |\n"
        f"| Duration ratio mean | {mc.get('duration_ratio_mean', 'N/A')} "
        f"(std: {mc.get('duration_ratio_std', 'N/A')}) |\n"
        f"| Sample tasks | {mc.get('n_ratio_samples', 0)} completed tasks |\n\n"
        f"> *{mc.get('caveat', '')}*\n"
    )


def _cluster_section(cluster: dict) -> str:
    if not cluster.get("clusters"):
        return f"> {cluster.get('headline', 'No cluster data.')}\n"

    lines = [f"**{cluster['headline']}**\n", f"*{cluster.get('caveat','')}*\n\n"]
    lines.append("| Cluster | Tasks | % of Risk | Top Area | Top Phase | Top Owner | Red Tasks |\n")
    lines.append("|---------|-------|-----------|----------|-----------|-----------|----------|\n")
    for c in cluster["clusters"]:
        lines.append(
            f"| {c['cluster_id']+1} | {c['task_count']} | {c['pct_of_risk']}% | "
            f"{c['top_area']} | {c['top_phase']} | {c['top_owner']} | {c['red_tasks']} |\n"
        )
    return "".join(lines)


def _delta_section(delta: dict) -> str:
    if not delta.get("has_previous"):
        return f"> {delta.get('note', 'First run.')}\n"

    direction = delta.get("direction", "→ stable")
    red_delta = delta.get("red_tasks_delta", 0)
    red_line  = (
        f"Red task count: +{red_delta} (↑ worse)" if red_delta > 0
        else f"Red task count: {red_delta} (↓ better)" if red_delta < 0
        else "Red task count: unchanged"
    )
    return (
        f"{delta['change_sentence']}\n\n"
        f"- Score delta: {delta['score_delta']:+.4f} ({direction})\n"
        f"- {red_line}\n"
        f"- Previous run: {delta['prev_run_date'][:10]}\n"
    )


def _shap_section(shap_info: dict) -> str:
    if shap_info.get("error"):
        return f"> SHAP: {shap_info['error']}\n"
    lines = [
        "| Feature | Mean |SHAP| |\n|---------|----------------|\n"
    ]
    for f in shap_info.get("top_features", []):
        lines.append(f"| {f['feature']} | {f['mean_abs_shap']} |\n")
    lines.append(f"\n> *{shap_info.get('disclaimer', '')}*\n")
    return "".join(lines)


def write_report(
    project_name: str,
    scores: dict[str, Any],
    mc: dict[str, Any],
    cluster: dict[str, Any],
    delta: dict[str, Any],
    shap_info: dict[str, Any],
    narrative: str,
    verified: bool,
    run_date: datetime | None = None,
    output_dir: str = config.WEEKLY_OUTPUT_DIR,
) -> Path:
    """
    Compose and write the full weekly Markdown report.
    Returns the path to the written file.
    """
    if run_date is None:
        run_date = datetime.now()

    date_str = run_date.strftime("%Y-%m-%d")
    safe_name = project_name.replace(" ", "_").replace("/", "-")
    filename = f"{date_str}_{safe_name}.md"

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    filepath = out_dir / filename

    rag = scores["rag"]
    summary = scores.get("task_summary", {})
    by_status = summary.get("by_status", {})
    by_rag    = summary.get("by_rag", {})
    crit      = scores.get("critical_path", {})
    dq        = scores.get("data_quality", {})

    verify_note = (
        "✅ LLM self-verified (no factual corrections needed)"
        if verified is True
        else "⚠️ LLM verification flagged corrections (applied)"
        if verified is False and config.USE_LLM
        else "ℹ️ Rule-based narrative (no LLM key)"
    )

    report = f"""# Weekly Project Health Report
**Project:** {project_name}
**Report Date:** {date_str}
**Generated by:** Zycus Project Health Agent

---

## 🏷️ Overall Status: {_rag_badge(rag)}

| Metric | Value |
|--------|-------|
| Project Score | {scores['project_score']:.3f} / 1.00 |
| Forward Risk | {scores['forward_risk']:.3f} |
| Historical Slip | {scores['historical_slip']:.3f} |
| Completed | {by_status.get('Completed', 0)} |
| In Progress | {by_status.get('In Progress', 0)} |
| Not Started | {by_status.get('Not Started', 0)} |
| On Hold | {by_status.get('On Hold', 0)} |
| 🔴 Red Tasks | {by_rag.get('Red', 0)} |
| 🟡 Yellow Tasks | {by_rag.get('Yellow', 0)} |
| 🟢 Green Tasks | {by_rag.get('Green', 0)} |
| Critical Path Tasks | {crit.get('total', 0)} |
| Red on Critical Path | {crit.get('by_rag', {}).get('Red', 0)} |

---

## 📝 Executive Summary

{narrative}

*{verify_note}*

---

## 📊 Week-on-Week Delta

{_delta_section(delta)}

---

## 🎲 Monte Carlo Deadline Forecast

{_mc_section(mc)}

---

## 🔍 Risk Concentration (Cluster Analysis)

{_cluster_section(cluster)}

---

## 🤖 ML Feature Importance (SHAP)

{_shap_section(shap_info)}

---

## ⚙️ Data Quality Notes

| Check | Value |
|-------|-------|
| Total tasks | {dq.get('total_tasks', 0)} |
| Tasks with RAG label | {dq.get('labeled_tasks', 0)} |
| Known sign-anomaly rows | {dq.get('sign_anomaly_rows', 0)} |

> Sign-anomaly rows: tasks where Variance sign appears inverted vs. computed
> date delta. Documented in `config.SIGN_INVERTED_TASKS`. Not silently dropped.

---

*Report generated: {run_date.isoformat()} | Agent version: 1.0*
"""

    filepath.write_text(report, encoding="utf-8")
    return filepath
